# Server Configuration
server.port=8081

# RabbitMQ Configuration
rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest
rabbitmq.pool.size=40

# Consumer Configuration
consumer.thread.count=20
consumer.prefetch.count=10

# Chat Configuration
chat.room.count=20

# Logging
logging.level.cs6650.assignment1=INFO
logging.level.org.springframework.amqp=DEBUG
logging.level.com.rabbitmq=DEBUG
